### ISSUE TITLE
Attribute error 

### ISSUE THREAD

**Issue by atcodedog32** [SeanNaren/CORD-19-ANN#7]
embeddings = model.encode_sentences(sentences=shuffled_sentences)

This above line of code is not working from this colab notebook; [https://colab.research.google.com/drive/137jbpY3yQJGSzlLHZGUYBk5F78bwuqKJ](url)

error: 'BertTokenizer' object has no attribute 'num_added_tokens'

**Comment by SeanNaren** [comment]
Hey thanks for your issue! It should be fixed now, seemed like the Tokenizers library updated and changed the name of the function call. I'm updating the collab notebook now so give me a few minutes!

**Comment by SeanNaren** [comment]
Should work now, I had to fix the version of UMAP which I'll investigate further

https://colab.research.google.com/drive/137jbpY3yQJGSzlLHZGUYBk5F78bwuqKJ#scrollTo=veWIDoS9p-QM

**Comment by atcodedog32** [comment]
Greetings!

Thanks a lot for fixing it and sharing the colab link!

cheers,
Archana
